# -*- coding: utf-8 -*-
"""SpeciesPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKBiS2qCSh_wtOizK7pRwnkGl0QnlFdc

**Species** **Prediction**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('speciesdata.csv')

x=df.iloc[:,1:-1].values

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

from sklearn.decomposition import PCA
pca=PCA(n_components=3)
x_temp=pca.fit_transform(x)
print(pca.explained_variance_ratio_)

print(x)

clusters=KMeans(n_clusters=3, init="k-means++", random_state=0)
clusters.fit(x)
y_pred=clusters.predict(x)
print(y_pred)

y_col=y_pred.reshape(len(y_pred),1)
output=np.append(arr=x_temp, values=y_col, axis=1)
print(output)

centroids = clusters.cluster_centers_
print(centroids)

from scipy.spatial import distance_matrix
dist_mat = pd.DataFrame(distance_matrix(x, centroids))

print(dist_mat)

dist_mat=np.array(dist_mat)
print(dist_mat)

for i in dist_mat:
  temp=sum(i)
  for j in range(0,3):
    i[j]=i[j]/temp
print(dist_mat)

dist_mat=pd.DataFrame(dist_mat)
print(dist_mat)

name=df.iloc[:,0]

final_output=pd.concat([name, dist_mat],axis=1)
final_output.columns.values[0]="id"
final_output.columns.values[1]="species1"
final_output.columns.values[2]="species2"
final_output.columns.values[3]="species3" 
print(final_output)